INSERT INTO familia(id, nombre)
VALUES
(1, 'Materiales de Escritura'),
(2, 'Cuadernos y Libretas'),
(3, 'Materiales de Arte'),
(4, 'Útiles de Oficina'),
(5, 'Mochilas y Cartucheras'),
(6, 'Papelería General'),
(7, 'Material Didáctico'),
(8, 'Adhesivos y Correctores'),
(9, 'Geometría y Dibujo'),
(10, 'Productos para Exámenes'),
(11, 'Libros y Textos'),
(12, 'Planners y Agendas'),
(13, 'Tecnología Escolar'),
(14, 'Manualidades'),
(15, 'Papel y Cartulinas'),
(16, 'Organizadores'),
(17, 'Productos para Profesores'),
(18, 'Merchandising Escolar'),
(19, 'Básicos Escolares'),
(20, 'Productos Especializados'),
(21, 'Material Preescolar'),
(22, 'Ofertas y Combos');
