INSERT INTO categoria (Categoria_Id, tipoCategoria, descripcionCateg)
VALUES
(1, 'Materiales de Escritura', 'Artículos como lápices, lapiceros y marcadores'),
(2, 'Cuadernos y Libretas', 'Variedad de cuadernos para distintas necesidades escolares'),
(3, 'Materiales de Arte', 'Materiales para dibujo, pintura y actividades artísticas'),
(4, 'Útiles de Oficina', 'Herramientas básicas para oficinas y estudios'),
(5, 'Mochilas y Cartucheras', 'Bolsas y estuches escolares'),
(6, 'Papelería General', 'Papeles, sobres y otros productos de papelería'),
(7, 'Material Didáctico', 'Recursos para apoyar la enseñanza'),
(8, 'Adhesivos y Correctores', 'Pegamentos, cintas adhesivas y correctores'),
(9, 'Geometría y Dibujo', 'Reglas, compases y sets de geometría'),
(10, 'Productos para Exámenes', 'Artículos requeridos para rendir exámenes'),
(11, 'Libros y Textos', 'Libros de lectura y libros de texto escolares'),
(12, 'Planners y Agendas', 'Agendas escolares y planificadores'),
(13, 'Tecnología Escolar', 'Calculadoras, tablets y otros dispositivos'),
(14, 'Manualidades', 'Materiales para actividades manuales y creativas'),
(15, 'Papel y Cartulinas', 'Papeles de colores y cartulinas para proyectos'),
(16, 'Organizadores', 'Organizadores, carpetas y archivos'),
(17, 'Productos para Profesores', 'Materiales de apoyo docente'),
(18, 'Merchandising Escolar', 'Productos promocionales escolares'),
(19, 'Básicos Escolares', 'Material escolar esencial y básico'),
(20, 'Productos Especializados', 'Material específico para materias técnicas'),
(21, 'Material Preescolar', 'Material para nivel inicial o preescolar'),
(22, 'Ofertas y Combos', 'Paquetes promocionales de productos escolares');
