INSERT INTO familia(id, nombre)
VALUES
(1, 'desayunos'),
(2, 'especialidades'),
(3, 'ceviches'),
(4, 'chaufas'),
(5, 'frituras'),
(6, 'duos y trios'),
(7, 'menu piurano'),
(8, 'criollos'),
(9, 'guarniciones'),
(10, 'fuentes'),
(11, 'chupes'),
(12, 'tortillas'),
(13, 'arroces'),
(14, 'chilcanos'),
(15, 'parihuelas'),
(16, 'sudados'),
(17, 'cena'),
(18, 'piqueos'),
(19, 'bebidas'),
(20, 'tragos'),
(21, 'vinos'),
(22, 'infusiones');
